name: "units-test"
on:
  release:
    types: [ published ]

jobs:
  # test action works running from the graph
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Bump Package Version
        uses: ./

      - name: Auto Commit Action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Bump Package Version
          commit_options: "--no-verify --signoff"
          file_pattern: package.json
